name: 'Github Actions Bitcoin Bot'

on:
    schedule:
        - cron: '*/30 */1 * * *'
    push:
    watch:
         types: [started]
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout codes
          uses: actions/checkout@v1
        - name: Get Result
          run: bash ./bitcoin.sh
        - name: Send mail
          uses: dawidd6/action-send-mail@master
          with:
            server_address: smtpout.secureserver.net2
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Bitcoin Rate Report
            body: file://result.html
            to: qaz3358258741232@protonmail.com
            from: GitHub Actions
            content_type: text/html
